# Generated by Django 5.0.4 on 2024-05-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingsetup',
            name='period',
            field=models.CharField(choices=[('раз в день', 'раз в день'), ('раз в неделю', 'раз в неделю'), ('раз в месяц', 'раз в месяц')], default='EVERY_DAY', max_length=20, verbose_name='периодичность'),
        ),
        migrations.AlterField(
            model_name='mailingsetup',
            name='status',
            field=models.CharField(choices=[('создана', 'создана'), ('запущена', 'запущена'), ('завершена', 'завершена')], default='STATUS_CREATE', max_length=20, verbose_name='статус рассылки'),
        ),
    ]
