# Generated by Django 4.2.2 on 2024-05-13 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_mailingsetup_period_alter_mailingsetup_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailingsetup',
            options={'permissions': [('can_disable_mailing', 'Может отключать рассылку')], 'verbose_name': 'настройка рассылки', 'verbose_name_plural': 'настройки рассылки'},
        ),
    ]
